apiVersion: v1
kind: Secret
metadata:
  name: llm-gateway-secret
type: Opaque
stringData:
  JWT_SECRET: "{{ .Values.adminApi.secret.jwtSecret }}"
  {{- if eq .Values.redis.mode "local" }}
  REDIS_URL: "redis://redis:6379"
  {{- end }}
  {{- if eq .Values.database.mode "local" }}
  DATABASE_URL: "postgres://{{ .Values.database.local.username }}:{{ .Values.database.local.password }}@postgres:5432/{{ .Values.database.local.database }}"
  {{- end }}
