{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pingora-gateway
spec:
  selector:
    matchLabels:
      app: pingora-gateway
  endpoints:
    - port: metrics
      path: /
{{- end }}
